/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package co.edu.unal.app;

import org.junit.jupiter.api.Test;

class MessageUtilsTest {

  @Test
  void testGetMessage() {
  }
}
